### ISSUE TITLE
sub normalize not exported

### ISSUE THREAD

**Issue by jacoby** [zostay/URI-Normalize#1]
I tried to use the module according to the POD:

```
use URI ;
use URI::Normalize qw{ normalize remove_dot_segments };
```

And found it didn't work:

```
"normalize" is not exported by the URI::Normalize module
Can't continue after import errors at ./test.pl line 12.
BEGIN failed--compilation aborted at ./test.pl line 12, <DATA> line 1.
```

noramize_uri IS exported and works. I could definitely see using this module, but documentation that says "Do this" and "this" doesn't work isn't helpful.

**Comment by zostay** [comment]
Thanks for the bug report. This is fixed in 0.002 and should show up on CPAN in the next few minutes.
